apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: eureka-service
spec:
  type: NodePort
  ports:
  - port: 8761
    protocol: TCP
    targetPort: 8761
    nodePort: 30000
  selector:
    tier: micro-ecosystem
