apiVersion: v1
kind: Pod
metadata: 
  name: pod-name
  labels:
    app: pod-name
  namespace: namespace-name
spec:
  containers:
    - name:
      image:
      env:
        - name:
          value:
      command: [""]
      args: [""]
      ports:
        - containerPort:
      volumeMounts:
        - mountPath:
          name:
  volumes:
    name:
    hostPath:
      path:
      type: Directory
      
---
apiVersion: v1
kind: Pod
metadata: 
  name: pod-name
  labels:
    app: pod-name
  namespace: namespace-name
spec:
  containers:
    - name:
      image:
      env:
        - name:
          value:
      command: [""]
      args: [""]
      ports:
        - containerPort:
      volumeMounts:
        - mountPath:
          name:
  volumes:
    name:
    persistentVolumeClaim:
      claimName: 