apiVersion: v1
kind: Service
metadata:
  name: service-name
  namespace: namespace-name
spec:
  type: ClusterIP
  ports:
    - port:
      targetPort: 
  selector:
---
apiVersion: v1
kind: Service
metadata:
  name: service-name
  namespace: namespace-name
spec:
  type: NodePort
  ports:
    - port:
      targetPort:
      nodePort: 
  selector:
---
apiVersion: v1
kind: Service
metadata:
  name: service-name
  namespace: namespace-name
spec:
  type: LoadBalancer
  ports:
    - port:
      targetPort:
      nodePort: 
  selector:    